// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "./transport";

/** Commands */
export const commands = {
	getPort: () => __TAURI_INVOKE<number>("get_port"),
	createSession: (source: string, options: ProcessingOptions) => typedError<SessionSnapshot, CommandError>(__TAURI_INVOKE("create_session", { source, options })),
	listSessions: () => typedError<SessionSnapshot[], CommandError>(__TAURI_INVOKE("list_sessions")),
	getSession: (sessionId: SessionId) => typedError<SessionSnapshot, CommandError>(__TAURI_INVOKE("get_session", { sessionId })),
	closeSession: (sessionId: SessionId) => typedError<ClosedSession, CommandError>(__TAURI_INVOKE("close_session", { sessionId })),
	initializeSession: (sessionId: SessionId) => typedError<OperationResponse<Revision>, CommandError>(__TAURI_INVOKE("initialize_session", { sessionId })),
	parseSession: (sessionId: SessionId, config: TocParserConfig) => typedError<OperationResponse<ParsedResults>, CommandError>(__TAURI_INVOKE("parse_session", { sessionId, config })),
	installResults: (sessionId: SessionId, expected: Revision, results: ParsedResults) => typedError<OperationResponse<Revision>, CommandError>(__TAURI_INVOKE("install_results", { sessionId, expected, results })),
	applyEdits: (sessionId: SessionId, expected: Revision, batch: EditBatch) => typedError<OperationResponse<Revision>, CommandError>(__TAURI_INVOKE("apply_edits", { sessionId, expected, batch })),
	setMetadataOverrides: (sessionId: SessionId, expected: Revision, overrides: Metadata) => typedError<OperationResponse<Revision>, CommandError>(__TAURI_INVOKE("set_metadata_overrides", { sessionId, expected, overrides })),
	readText: (sessionId: SessionId, version: DocumentVersion, range: TextRange) => typedError<OperationResponse<string>, CommandError>(__TAURI_INVOKE("read_text", { sessionId, version, range })),
	readResults: (sessionId: SessionId) => typedError<OperationResponse<WorkspaceResults>, CommandError>(__TAURI_INVOKE("read_results", { sessionId })),
	renderPreview: (sessionId: SessionId, expected: Revision, options: ExportOptions) => typedError<OperationResponse<PreviewInfo>, CommandError>(__TAURI_INVOKE("render_preview", { sessionId, expected, options })),
	exportEpub: (sessionId: SessionId, expected: Revision, options: ExportOptions, destination: string) => typedError<OperationResponse<ExportedBook>, CommandError>(__TAURI_INVOKE("export_epub", { sessionId, expected, options, destination })),
	cancelOperation: (sessionId: SessionId, operationId: OperationId) => typedError<CancelReply, CommandError>(__TAURI_INVOKE("cancel_operation", { sessionId, operationId })),
};

/* Constants */
export const DESKTOP_ONLY_COMMANDS = ["get_port"] as const;

/* Types */
export type Activity = "Idle" | { Running: {
	op: OperationId,
	kind: OpKind,
	phase: Phase | null,
	cancel_requested: boolean,
} };

export type Availability = ({ Available: WorkspaceStatus }) & { Lost?: never } | ({ Lost: {
	last_revision: Revision,
} }) & { Available?: never };

export type CancelReply = "Requested" | "NotActive";

export type ChapterMode = ({ Rules: HeadingRuleConfig[] }) & { EndMarker?: never } | ({ EndMarker: {
	marker: string,
} }) & { Rules?: never };

export type CleanupWarning = {
	path: string,
	message: string,
};

export type ClosedSession = {
	last: OperationSummary | null,
	lost: boolean,
	cleanup_failures: CleanupWarning[],
};

export type CommandError = {
	kind: ErrorKind,
	message: string,
};

export type DocumentStatus = "Absent" | "Unparsed" | "Current" | "Stale";

export type DocumentVersion = {
	document_id: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number],
	revision: number,
};

export type EditBatch = {
	base: DocumentVersion,
	edits: TextEdit[],
};

export type ErrorKind = "invalid_params" | "method_not_found" | "platform_unsupported" | "not_found" | "shutting_down" | "busy" | "unavailable" | "closing" | "closed" | "invalid_config" | "stale_revision" | "no_document" | "already_initialized" | "results_not_current" | "read_too_large" | "cancelled" | "panicked" | "extractor" | "document" | "pipeline" | "export" | "internal_error";

export type ExportOptions = {
	render: RenderOptions,
	format: OutputFormat,
	language: string,
	identifier: string | null,
};

export type ExportedBook = {
	revision: Revision,
	format: OutputFormat,
	path: string,
	version: DocumentVersion,
	identifier: string,
	cleanup_failures: CleanupWarning[],
};

export type FilterConfig = "Ad";

export type FilterProgress = {
	applied: number,
	total: number,
};

export type HeadingRuleConfig = ({ Simple: SimpleRuleConfig }) & { Regex?: never } | ({ Regex: PatternRuleConfig }) & { Simple?: never };

export type LevelRulesConfig = {
	level: number,
	rules: HeadingRuleConfig[],
};

export type LifecycleState = "Open" | "Closing" | "Closed";

export type Metadata = {
	title: string | null,
	author: string | null,
};

/**
 *  Strongly typed id of a TOC node. Internally it is a slab key, so
 *  serialization is free (`serde(transparent)`).
 *
 *  Caveat: slab reuses the keys of removed nodes, so a stale `NodeId` held
 *  after a `remove` may alias a newly inserted node. If that ever becomes a
 *  problem, switch the container to `generational-arena`.
 */
export type NodeId = number;

export type NumeralStyle = "Arabic" | "Chinese" | "Mixed";

export type OpKind = "Initialize" | "Parse" | "Install" | "Edit" | "SetMetadataOverrides" | "ReadText" | "ReadResults" | "RenderPreview" | "ExportEpub";

export type OperationId = number;

export type OperationResponse<T> = {
	op: OperationId,
	kind: OpKind,
	revision: Revision,
	outcome: Outcome<T>,
	warnings: CleanupWarning[],
};

export type OperationSummary = {
	op: OperationId,
	kind: OpKind,
	revision: Revision,
	category: ResultCategory,
};

export type Outcome<T> = { status: "ok"; data: T } | { status: "error"; error: CommandError };

export type OutputFormat = "Epub";

export type ParsedResults = {
	version: DocumentVersion,
	toc: TocRoot,
	metadata: Metadata,
};

export type PatternRuleConfig = {
	pattern: string,
	title_group: number | null,
};

export type Phase = "Extracting" | { Filtering: {
	index: number,
	total: number,
} } | "Parsing" | "Installing" | "Editing" | "Reading" | "Rendering" | "Exporting";

export type PreviewInfo = {
	revision: Revision,
	options: ExportOptions,
	directory: string,
	files: string[],
};

export type ProcessingOptions = {
	filters: FilterConfig[],
	toc: TocParserConfig,
};

export type RenderLayout = "SplitChapters" | "Paged" | "SingleHtml";

export type RenderOptions = {
	layout: RenderLayout,
};

export type ResultCategory = "Succeeded" | "Failed" | "Cancelled" | "Panicked";

export type Revision = number;

export type SessionId = number;

export type SessionSnapshot = {
	seq: number,
	session: SessionId,
	workspace: WorkspaceId,
	source: string,
	lifecycle: LifecycleState,
	activity: Activity,
	workspace_status: Availability,
	last: OperationSummary | null,
};

export type SimpleRuleConfig = {
	allow_leading_space: boolean,
	prefixes: string[],
	numeral: NumeralStyle,
	suffixes: string[],
	min_numeral_len: number,
	max_numeral_len: number | null,
	max_title_len: number,
};

export type TextEdit = {
	range: TextRange,
	insert: string,
};

/** A UTF-8 byte range interpreted in the document version supplied by its owner. */
export type TextRange = {
	start: number,
	end: number,
};

/**  Wire-format TOC entry (aligned with calibre's "TOC entry" terminology). */
export type TocEntry = {
	id: NodeId,
	title: string,
	meta: TreeNodeMeta,
	children: TocEntry[],
};

export type TocParserConfig = ({ Levels: TocRulesConfig }) & { SplitEvenly?: never; VBook?: never } | ({ VBook: VBookConfig }) & { Levels?: never; SplitEvenly?: never } | ({ SplitEvenly: {
	parts: number,
} }) & { Levels?: never; VBook?: never };

export type TocRangeKind = "Heading" | "Body" | "Container" | "Unknown";

export type TocRoot = {
	id: NodeId,
	title: string,
	meta: TreeNodeMeta,
	children: TocEntry[],
}[];

export type TocRulesConfig = {
	levels: LevelRulesConfig[],
};

export type TreeNodeMeta = {
	words: number,
	range_kind?: TocRangeKind,
	/**
	 *  The content range of the node itself. `None` for pure container nodes
	 *  (like calibre TOC entries whose src points at their first child).
	 */
	range: TextRange | null,
};

export type VBookConfig = {
	chapters: ChapterMode,
	volumes: VolumeMode,
};

export type VolumeMode = "None" | ({ Normal: {
	rules: HeadingRuleConfig[],
	fallback_chapters_per_volume: number | null,
} }) & { Forced?: never; FromChapterTitles?: never } | ({ FromChapterTitles: {
	rules: HeadingRuleConfig[],
} }) & { Forced?: never; Normal?: never } | ({ Forced: {
	chapters_per_volume: number,
} }) & { FromChapterTitles?: never; Normal?: never };

export type WorkspaceId = [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];

export type WorkspaceResults = {
	results: ParsedResults | null,
	current: boolean,
	overrides: Metadata,
};

export type WorkspaceStatus = {
	revision: Revision,
	document: DocumentStatus,
	document_version: DocumentVersion | null,
	filters: FilterProgress,
	has_overrides: boolean,
	preview: ExportOptions | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}
