// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "./transport";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getPort: () => __TAURI_INVOKE<number>("get_port"),
	getSettings: () => __TAURI_INVOKE<StoredSettings>("get_settings"),
	defaultSettings: () => __TAURI_INVOKE<Settings>("default_settings"),
	builtinTemplates: () => __TAURI_INVOKE<TemplateOverrides>("builtin_templates"),
	listSessions: () => __TAURI_INVOKE<SessionSnapshot[]>("list_sessions"),
	getSession: (sessionId: SessionId) => __TAURI_INVOKE<SessionSnapshot>("get_session", { sessionId }),
	getSessionSettings: (sessionId: SessionId) => __TAURI_INVOKE<Settings>("get_session_settings", { sessionId }),
	readText: (sessionId: SessionId, version: DocumentVersion, range: TextRange) => __TAURI_INVOKE<OperationResponse<string>>("read_text", { sessionId, version, range }),
	readResults: (sessionId: SessionId) => __TAURI_INVOKE<OperationResponse<WorkspaceResults_Serialize>>("read_results", { sessionId }),
	openSessionWindow: (sessionId: SessionId) => __TAURI_INVOKE<null>("open_session_window", { sessionId }),
	openSettingsWindow: () => __TAURI_INVOKE<null>("open_settings_window"),
	openSessionSettingsWindow: (sessionId: SessionId) => __TAURI_INVOKE<null>("open_session_settings_window", { sessionId }),
	/**  Opens a web page to pick a cover from; picks arrive as `CoverPicked`. */
	openCoverSearch: (sessionId: SessionId, url: string) => __TAURI_INVOKE<null>("open_cover_search", { sessionId, url }),
	/**  Downloads a picked image and makes it the cover. */
	setCoverFromUrl: (sessionId: SessionId, expected: Revision, url: string, referer: string | null) => __TAURI_INVOKE<OperationResponse<Revision>>("set_cover_from_url", { sessionId, expected, url, referer }),
	windowReady: () => __TAURI_INVOKE<null>("window_ready"),
	saveSettings: (expected: number, settings: Settings) => __TAURI_INVOKE<StoredSettings>("save_settings", { expected, settings }),
	/**  The session starts from a copy of the current global settings. */
	createSession: (source: string) => __TAURI_INVOKE<SessionSnapshot>("create_session", { source }),
	closeSession: (sessionId: SessionId) => __TAURI_INVOKE<ClosedSession>("close_session", { sessionId }),
	initializeSession: (sessionId: SessionId) => __TAURI_INVOKE<OperationResponse<Revision>>("initialize_session", { sessionId }),
	setSessionSettings: (sessionId: SessionId, expected: Revision, settings: Settings) => __TAURI_INVOKE<OperationResponse<Revision>>("set_session_settings", { sessionId, expected, settings }),
	parseSession: (sessionId: SessionId) => __TAURI_INVOKE<OperationResponse<ParsedResults_Serialize>>("parse_session", { sessionId }),
	installResults: (sessionId: SessionId, expected: Revision, results: ParsedResults_Deserialize) => __TAURI_INVOKE<OperationResponse<Revision>>("install_results", { sessionId, expected, results }),
	applyEdits: (sessionId: SessionId, expected: Revision, batch: EditBatch) => __TAURI_INVOKE<OperationResponse<Revision>>("apply_edits", { sessionId, expected, batch }),
	setMetadataOverrides: (sessionId: SessionId, expected: Revision, overrides: Metadata) => __TAURI_INVOKE<OperationResponse<Revision>>("set_metadata_overrides", { sessionId, expected, overrides }),
	/**  `image` is base64, so the browser bridge can carry it in JSON. */
	setCoverImage: (sessionId: SessionId, expected: Revision, image: string | null) => __TAURI_INVOKE<OperationResponse<Revision>>("set_cover_image", { sessionId, expected, image }),
	renderCover: (sessionId: SessionId) => __TAURI_INVOKE<OperationResponse<RenderedCover>>("render_cover", { sessionId }),
	renderPreview: (sessionId: SessionId, expected: Revision) => __TAURI_INVOKE<OperationResponse<PreviewInfo>>("render_preview", { sessionId, expected }),
	exportEpub: (sessionId: SessionId, expected: Revision, destination: string) => __TAURI_INVOKE<OperationResponse<ExportedBook>>("export_epub", { sessionId, expected, destination }),
	cancelOperation: (sessionId: SessionId, operationId: OperationId) => __TAURI_INVOKE<CancelReply>("cancel_operation", { sessionId, operationId }),
};

/** Events */
export const events = {
	coverPicked: makeEvent<CoverPicked, CoverPicked>("cover-picked"),
	sessionClosed: makeEvent<SessionClosed, SessionClosed>("session-closed"),
};

/* Constants */
export const DESKTOP_ONLY_COMMANDS = ["get_port","open_session_window","open_settings_window","open_session_settings_window","open_cover_search","set_cover_from_url","window_ready"] as const;

/* Types */
export type Activity = "Idle" | { Running: {
	op: OperationId,
	kind: OpKind,
	phase: Phase | null,
	cancel_requested: boolean,
} };

export type Availability = ({ Available: WorkspaceStatus }) & { Lost?: never } | ({ Lost: {
	last_revision: Revision,
} }) & { Available?: never };

export type CancelReply = "Requested" | "NotActive";

export type CleanupWarning = {
	path: string,
	message: string,
};

export type ClosedSession = {
	last: OperationSummary | null,
	lost: boolean,
	cleanup_failures: CleanupWarning[],
};

export type CommandError = {
	kind: ErrorKind,
	message: string,
};

export type CoverKind = "None" | "Generated" |
/**  The image the user chose for this book. */
"Image";

/**  Sent to the session window when an image was picked in its search window. */
export type CoverPicked = {
	session: SessionId,
	url: string,
	/**  The page the image was shown on; some hosts refuse hotlinks without it. */
	referer: string | null,
};

export type CoverSearchSettings = {
	/**  The initial search text; `{title}` and `{author}` are replaced. */
	query: string,
	engines: SearchEngine[],
};

export type CoverSettings = {
	kind: CoverKind,
	/**
	 *  Draws the title and author over a custom image; the generated cover
	 *  always shows them.
	 */
	overlay: boolean,
	/**  E-ink readers show color covers with poor contrast. */
	grayscale: boolean,
};

export type DocumentStatus = "Absent" | "Unparsed" | "Current" | "Stale";

export type DocumentVersion = {
	document_id: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number],
	revision: number,
};

export type EditBatch = {
	base: DocumentVersion,
	edits: TextEdit[],
};

export type ErrorKind = "invalid_params" | "method_not_found" | "platform_unsupported" | "not_found" | "shutting_down" | "busy" | "unavailable" | "closing" | "closed" | "invalid_config" | "stale_revision" | "no_document" | "already_initialized" | "results_not_current" | "read_too_large" | "cancelled" | "panicked" | "extractor" | "document" | "pipeline" | "export" | "network" | "internal_error";

export type ExportOptions = {
	render: RenderOptions,
	format: OutputFormat,
	language: string,
	identifier: string | null,
	cover: CoverSettings,
};

export type ExportedBook = {
	revision: Revision,
	format: OutputFormat,
	path: string,
	version: DocumentVersion,
	identifier: string,
	cleanup_failures: CleanupWarning[],
};

export type FilterConfig = "Ad";

export type FilterProgress = {
	applied: number,
	total: number,
};

export type LifecycleState = "Open" | "Closing" | "Closed";

export type Metadata = {
	title: string | null,
	author: string | null,
	/**  ISBN-10 or ISBN-13 as typed; it is packaged without separators. */
	isbn: string | null,
	publisher: string | null,
	/**  `YYYY`, `YYYY-MM` or `YYYY-MM-DD`, the date forms EPUB requires. */
	published: string | null,
	description: string | null,
};

/**
 *  Strongly typed id of a TOC node. Internally it is a slab key, so
 *  serialization is free (`serde(transparent)`).
 *
 *  Caveat: slab reuses the keys of removed nodes, so a stale `NodeId` held
 *  after a `remove` may alias a newly inserted node. If that ever becomes a
 *  problem, switch the container to `generational-arena`.
 */
export type NodeId = number;

export type OpKind = "Initialize" | "Parse" | "Install" | "Edit" | "SetMetadataOverrides" | "SetSettings" | "SetCoverImage" | "RenderCover" | "ReadText" | "ReadResults" | "RenderPreview" | "ExportEpub";

export type OperationId = number;

export type OperationResponse<T> = {
	op: OperationId,
	kind: OpKind,
	revision: Revision,
	outcome: Outcome<T>,
	warnings: CleanupWarning[],
};

export type OperationSummary = {
	op: OperationId,
	kind: OpKind,
	revision: Revision,
	category: ResultCategory,
};

export type Outcome<T> = { status: "ok"; data: T } | { status: "error"; error: CommandError };

export type OutputFormat = "Epub";

export type ParsedResults = ParsedResults_Serialize | ParsedResults_Deserialize;

export type ParsedResults_Deserialize = {
	version: DocumentVersion,
	toc: TocRoot_Deserialize,
	metadata: Metadata,
};

export type ParsedResults_Serialize = {
	version: DocumentVersion,
	toc: TocRoot_Serialize,
	metadata: Metadata,
};

export type Phase = "Extracting" | { Filtering: {
	index: number,
	total: number,
} } | "Parsing" | "Installing" | "Editing" | "Reading" | "Rendering" | "Exporting";

export type PreviewInfo = {
	id: string,
	revision: Revision,
	options: ExportOptions,
	directory: string,
	files: string[],
};

export type RenderLayout = "SplitChapters" | "Paged" | "SingleHtml";

export type RenderOptions = {
	layout: RenderLayout,
	templates: TemplateOverrides,
};

export type RenderSettings = {
	layout: RenderLayout,
	language: string,
	templates: TemplateOverrides,
};

/**  The cover as base64 JPEG, or `None` for a book without a cover. */
export type RenderedCover = {
	jpeg: string | null,
};

export type ResultCategory = "Succeeded" | "Failed" | "Cancelled" | "Panicked";

export type Revision = number;

export type SearchEngine = {
	name: string,
	/**  An http(s) address in which `{query}` is replaced by the search text. */
	url: string,
};

/**
 *  Sent to the main window once a windowed session has closed, so its list
 *  drops the session without waiting for focus.
 */
export type SessionClosed = {
	session: SessionId,
};

export type SessionId = number;

export type SessionSnapshot = {
	seq: number,
	session: SessionId,
	workspace: WorkspaceId,
	source: string,
	lifecycle: LifecycleState,
	activity: Activity,
	workspace_status: Availability,
	last: OperationSummary | null,
};

export type Settings = {
	toc: TocSettings,
	/**  Filters run once, when the session is initialized. */
	filters: FilterConfig[],
	render: RenderSettings,
	/**  The custom image itself is stored with the book, not here. */
	cover: CoverSettings,
	/**  Used from the global settings only; a session's copy is ignored. */
	cover_search: CoverSearchSettings,
};

export type StoredSettings = {
	settings: Settings,
	/**
	 *  Counts saves since startup so concurrent editors cannot overwrite
	 *  each other. Not persisted: one process owns the file.
	 */
	revision: number,
	/**
	 *  Why the settings file could not be used. The defaults stand in until
	 *  the next save replaces the file.
	 */
	problem: string | null,
};

/**
 *  Replacements for the built-in stylesheet and XHTML fragments; `None`
 *  keeps the built-in one. The package document and navigation entries are
 *  not replaceable because validation depends on their structure.
 */
export type TemplateOverrides = {
	stylesheet: string | null,
	document: string | null,
	section: string | null,
	paragraph: string | null,
};

export type TextEdit = {
	range: TextRange,
	insert: string,
};

/** A UTF-8 byte range interpreted in the document version supplied by its owner. */
export type TextRange = {
	start: number,
	end: number,
};

/**  Wire-format TOC entry (aligned with calibre's "TOC entry" terminology). */
export type TocEntry = TocEntry_Serialize | TocEntry_Deserialize;

/**  Wire-format TOC entry (aligned with calibre's "TOC entry" terminology). */
export type TocEntry_Deserialize = {
	id: NodeId,
	title: string,
	meta: TreeNodeMeta_Deserialize,
	children: TocEntry_Deserialize[],
};

/**  Wire-format TOC entry (aligned with calibre's "TOC entry" terminology). */
export type TocEntry_Serialize = {
	id: NodeId,
	title: string,
	meta: TreeNodeMeta_Serialize,
	children: TocEntry_Serialize[],
};

export type TocMode =
/**  Chapters grouped into volumes by volume headings or by count. */
"VBook" | "Chapters" |
/**  Two levels: volume headings above chapter headings. */
"Volumes" |
/**  No headings; split the text evenly. */
"Split";

export type TocRangeKind = "Heading" | "Body" | "Container" | "Unknown";

export type TocRoot = TocRoot_Serialize | TocRoot_Deserialize;

export type TocRoot_Deserialize = TocEntry_Deserialize[];

export type TocRoot_Serialize = TocEntry_Serialize[];

/**
 *  The user-facing parser options; [`TocSettings::to_config`] expands them
 *  into the general rule configuration.
 */
export type TocSettings = {
	mode: TocMode,
	chapter_marks: string[],
	volume_marks: string[],
	max_title_len: number,
	volume_split: VolumeSplit,
	/**
	 *  In VBook mode, also sizes the volumes for chapters before the first
	 *  volume heading.
	 */
	chapters_per_volume: number,
	parts: number,
};

export type TreeNodeMeta = TreeNodeMeta_Serialize | TreeNodeMeta_Deserialize;

export type TreeNodeMeta_Deserialize = {
	words: number,
	range_kind?: TocRangeKind,
	/**
	 *  The content range of the node itself. `None` for pure container nodes
	 *  (like calibre TOC entries whose src points at their first child).
	 */
	range: TextRange | null,
};

export type TreeNodeMeta_Serialize = {
	words: number,
	range_kind: TocRangeKind,
	/**
	 *  The content range of the node itself. `None` for pure container nodes
	 *  (like calibre TOC entries whose src points at their first child).
	 */
	range: TextRange | null,
};

export type VolumeSplit = "Titles" | "Forced" | "None";

export type WorkspaceId = [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];

export type WorkspaceResults = WorkspaceResults_Serialize | WorkspaceResults_Deserialize;

export type WorkspaceResults_Deserialize = {
	results: ParsedResults_Deserialize | null,
	current: boolean,
	overrides: Metadata,
};

export type WorkspaceResults_Serialize = {
	results: ParsedResults_Serialize | null,
	current: boolean,
	overrides: Metadata,
};

export type WorkspaceStatus = {
	revision: Revision,
	document: DocumentStatus,
	document_version: DocumentVersion | null,
	/**  Lets clients bound the last chapter, which has no following heading. */
	document_len: number | null,
	filters: FilterProgress,
	has_overrides: boolean,
	cover_image: boolean,
	preview: ExportOptions | null,
	preview_id: string | null,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<TListen, TEmit = TListen>(name: string, serialize?: (payload: TEmit) => unknown, deserialize?: (payload: any) => TListen) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<TListen>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: TEmit) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<TListen>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<TListen>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: TEmit) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<TEmit>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<TListen>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<TListen>) => target.once(name, mapEvent(cb)),
        emit: ((payload: TEmit) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<TEmit>
    });

    return Object.assign(fn, base);
}

/** Tanstack Query */
import { mutationOptions, queryOptions } from '@tanstack/react-query';

export const queries = {
	getPort: (...args: Parameters<typeof commands.getPort>) => queryOptions({ queryKey: ["getPort", ...args], queryFn: () => commands.getPort(...args) }),
	getSettings: (...args: Parameters<typeof commands.getSettings>) => queryOptions({ queryKey: ["getSettings", ...args], queryFn: () => commands.getSettings(...args) }),
	defaultSettings: (...args: Parameters<typeof commands.defaultSettings>) => queryOptions({ queryKey: ["defaultSettings", ...args], queryFn: () => commands.defaultSettings(...args) }),
	builtinTemplates: (...args: Parameters<typeof commands.builtinTemplates>) => queryOptions({ queryKey: ["builtinTemplates", ...args], queryFn: () => commands.builtinTemplates(...args) }),
	listSessions: (...args: Parameters<typeof commands.listSessions>) => queryOptions({ queryKey: ["listSessions", ...args], queryFn: () => commands.listSessions(...args) }),
	getSession: (...args: Parameters<typeof commands.getSession>) => queryOptions({ queryKey: ["getSession", ...args], queryFn: () => commands.getSession(...args) }),
	getSessionSettings: (...args: Parameters<typeof commands.getSessionSettings>) => queryOptions({ queryKey: ["getSessionSettings", ...args], queryFn: () => commands.getSessionSettings(...args) }),
	readText: (...args: Parameters<typeof commands.readText>) => queryOptions({ queryKey: ["readText", ...args], queryFn: () => commands.readText(...args) }),
	readResults: (...args: Parameters<typeof commands.readResults>) => queryOptions({ queryKey: ["readResults", ...args], queryFn: () => commands.readResults(...args) }),
};
export const queryKeys = {
	getPort: (...args: Partial<Parameters<typeof commands.getPort>>) => ["getPort", ...args],
	getSettings: (...args: Partial<Parameters<typeof commands.getSettings>>) => ["getSettings", ...args],
	defaultSettings: (...args: Partial<Parameters<typeof commands.defaultSettings>>) => ["defaultSettings", ...args],
	builtinTemplates: (...args: Partial<Parameters<typeof commands.builtinTemplates>>) => ["builtinTemplates", ...args],
	listSessions: (...args: Partial<Parameters<typeof commands.listSessions>>) => ["listSessions", ...args],
	getSession: (...args: Partial<Parameters<typeof commands.getSession>>) => ["getSession", ...args],
	getSessionSettings: (...args: Partial<Parameters<typeof commands.getSessionSettings>>) => ["getSessionSettings", ...args],
	readText: (...args: Partial<Parameters<typeof commands.readText>>) => ["readText", ...args],
	readResults: (...args: Partial<Parameters<typeof commands.readResults>>) => ["readResults", ...args],
};
export const mutations = {
	openSessionWindow: () => mutationOptions({ mutationKey: ["openSessionWindow"], mutationFn: (input: { sessionId: Parameters<typeof commands.openSessionWindow>[0] }) => commands.openSessionWindow(input.sessionId) }),
	openSettingsWindow: () => mutationOptions({ mutationKey: ["openSettingsWindow"], mutationFn: () => commands.openSettingsWindow() }),
	openSessionSettingsWindow: () => mutationOptions({ mutationKey: ["openSessionSettingsWindow"], mutationFn: (input: { sessionId: Parameters<typeof commands.openSessionSettingsWindow>[0] }) => commands.openSessionSettingsWindow(input.sessionId) }),
	openCoverSearch: () => mutationOptions({ mutationKey: ["openCoverSearch"], mutationFn: (input: { sessionId: Parameters<typeof commands.openCoverSearch>[0]; url: Parameters<typeof commands.openCoverSearch>[1] }) => commands.openCoverSearch(input.sessionId, input.url) }),
	setCoverFromUrl: () => mutationOptions({ mutationKey: ["setCoverFromUrl"], mutationFn: (input: { sessionId: Parameters<typeof commands.setCoverFromUrl>[0]; expected: Parameters<typeof commands.setCoverFromUrl>[1]; url: Parameters<typeof commands.setCoverFromUrl>[2]; referer: Parameters<typeof commands.setCoverFromUrl>[3] }) => commands.setCoverFromUrl(input.sessionId, input.expected, input.url, input.referer) }),
	windowReady: () => mutationOptions({ mutationKey: ["windowReady"], mutationFn: () => commands.windowReady() }),
	saveSettings: () => mutationOptions({ mutationKey: ["saveSettings"], mutationFn: (input: { expected: Parameters<typeof commands.saveSettings>[0]; settings: Parameters<typeof commands.saveSettings>[1] }) => commands.saveSettings(input.expected, input.settings) }),
	createSession: () => mutationOptions({ mutationKey: ["createSession"], mutationFn: (input: { source: Parameters<typeof commands.createSession>[0] }) => commands.createSession(input.source) }),
	closeSession: () => mutationOptions({ mutationKey: ["closeSession"], mutationFn: (input: { sessionId: Parameters<typeof commands.closeSession>[0] }) => commands.closeSession(input.sessionId) }),
	initializeSession: () => mutationOptions({ mutationKey: ["initializeSession"], mutationFn: (input: { sessionId: Parameters<typeof commands.initializeSession>[0] }) => commands.initializeSession(input.sessionId) }),
	setSessionSettings: () => mutationOptions({ mutationKey: ["setSessionSettings"], mutationFn: (input: { sessionId: Parameters<typeof commands.setSessionSettings>[0]; expected: Parameters<typeof commands.setSessionSettings>[1]; settings: Parameters<typeof commands.setSessionSettings>[2] }) => commands.setSessionSettings(input.sessionId, input.expected, input.settings) }),
	parseSession: () => mutationOptions({ mutationKey: ["parseSession"], mutationFn: (input: { sessionId: Parameters<typeof commands.parseSession>[0] }) => commands.parseSession(input.sessionId) }),
	installResults: () => mutationOptions({ mutationKey: ["installResults"], mutationFn: (input: { sessionId: Parameters<typeof commands.installResults>[0]; expected: Parameters<typeof commands.installResults>[1]; results: Parameters<typeof commands.installResults>[2] }) => commands.installResults(input.sessionId, input.expected, input.results) }),
	applyEdits: () => mutationOptions({ mutationKey: ["applyEdits"], mutationFn: (input: { sessionId: Parameters<typeof commands.applyEdits>[0]; expected: Parameters<typeof commands.applyEdits>[1]; batch: Parameters<typeof commands.applyEdits>[2] }) => commands.applyEdits(input.sessionId, input.expected, input.batch) }),
	setMetadataOverrides: () => mutationOptions({ mutationKey: ["setMetadataOverrides"], mutationFn: (input: { sessionId: Parameters<typeof commands.setMetadataOverrides>[0]; expected: Parameters<typeof commands.setMetadataOverrides>[1]; overrides: Parameters<typeof commands.setMetadataOverrides>[2] }) => commands.setMetadataOverrides(input.sessionId, input.expected, input.overrides) }),
	setCoverImage: () => mutationOptions({ mutationKey: ["setCoverImage"], mutationFn: (input: { sessionId: Parameters<typeof commands.setCoverImage>[0]; expected: Parameters<typeof commands.setCoverImage>[1]; image: Parameters<typeof commands.setCoverImage>[2] }) => commands.setCoverImage(input.sessionId, input.expected, input.image) }),
	renderCover: () => mutationOptions({ mutationKey: ["renderCover"], mutationFn: (input: { sessionId: Parameters<typeof commands.renderCover>[0] }) => commands.renderCover(input.sessionId) }),
	renderPreview: () => mutationOptions({ mutationKey: ["renderPreview"], mutationFn: (input: { sessionId: Parameters<typeof commands.renderPreview>[0]; expected: Parameters<typeof commands.renderPreview>[1] }) => commands.renderPreview(input.sessionId, input.expected) }),
	exportEpub: () => mutationOptions({ mutationKey: ["exportEpub"], mutationFn: (input: { sessionId: Parameters<typeof commands.exportEpub>[0]; expected: Parameters<typeof commands.exportEpub>[1]; destination: Parameters<typeof commands.exportEpub>[2] }) => commands.exportEpub(input.sessionId, input.expected, input.destination) }),
	cancelOperation: () => mutationOptions({ mutationKey: ["cancelOperation"], mutationFn: (input: { sessionId: Parameters<typeof commands.cancelOperation>[0]; operationId: Parameters<typeof commands.cancelOperation>[1] }) => commands.cancelOperation(input.sessionId, input.operationId) }),
};
export const mutationKeys = {
	openSessionWindow: () => ["openSessionWindow"],
	openSettingsWindow: () => ["openSettingsWindow"],
	openSessionSettingsWindow: () => ["openSessionSettingsWindow"],
	openCoverSearch: () => ["openCoverSearch"],
	setCoverFromUrl: () => ["setCoverFromUrl"],
	windowReady: () => ["windowReady"],
	saveSettings: () => ["saveSettings"],
	createSession: () => ["createSession"],
	closeSession: () => ["closeSession"],
	initializeSession: () => ["initializeSession"],
	setSessionSettings: () => ["setSessionSettings"],
	parseSession: () => ["parseSession"],
	installResults: () => ["installResults"],
	applyEdits: () => ["applyEdits"],
	setMetadataOverrides: () => ["setMetadataOverrides"],
	setCoverImage: () => ["setCoverImage"],
	renderCover: () => ["renderCover"],
	renderPreview: () => ["renderPreview"],
	exportEpub: () => ["exportEpub"],
	cancelOperation: () => ["cancelOperation"],
};
